name: CI
on:
  push:
    branches:
      - master
  schedule:
    # 每个月 1 号上午 9 点自动执行
    - cron:  "0 9 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 构建
        run: |
          yarn
          yarn start

      - name: 部署
        run: |
          git branch -v
          git config --global user.email "1162275271@qq.com"
          git config --global user.name "lblblong"
          git checkout -b dist
          rm -rf `ls|egrep -v '(.git|dist)'`
          rm .gitignore
          rm -rf .github
          mv ./dist/* .
          git add .
          git commit -m "更新城市数据"
          git push origin dist -f
